# Generated by Django 4.1.3 on 2022-11-14 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(default='***', max_length=100)),
                ('role', models.CharField(choices=[('EMPLOYER', 'EMPLOYER'), ('EMPLOYEE', 'EMPLOYEE')], default='EMPLOYEE', max_length=30)),
                ('is_employer', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('employer_image', models.ImageField(default='images/employer/default_profile.png', max_length=255, upload_to='images/employer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('district', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('venue', models.CharField(max_length=240)),
                ('vaccancy_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/vaccancy')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('contact', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=50)),
                ('qualifications', models.TextField(max_length=500)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='EMPLOYEE', max_length=16)),
                ('employee_image', models.ImageField(default='images/employer/default_profile.png', max_length=255, upload_to='images/employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('vaccancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccancy')),
            ],
        ),
    ]
