# Generated by Django 4.1.2 on 2022-10-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
    ]
