# Generated by Django 4.1.2 on 2022-10-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_address_remove_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
