# Generated by Django 4.1.2 on 2022-10-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
