# Generated by Django 4.1.2 on 2022-10-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employer_employer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer'),
        ),
    ]
