# Generated by Django 4.1.2 on 2022-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activity_options_alter_activity_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/activity/'),
        ),
    ]
