# Generated by Django 4.1.2 on 2022-10-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activity_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
    ]
