# Generated by Django 4.1.2 on 2022-10-19 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_activity_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='if_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/activity'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/employer'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('qualifications', models.CharField(max_length=500, null=True)),
                ('employer_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
