# Generated by Django 4.1.2 on 2022-10-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_if_employee_user_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
