# Generated by Django 4.1.2 on 2022-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_employee_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
