# Generated by Django 4.1.2 on 2022-10-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
    ]
