# Generated by Django 4.1.2 on 2022-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('1', 'PENDING'), ('2', 'ACCEPTED'), ('3', 'REJECTED')], default='PENDING', max_length=30),
        ),
    ]
