# Generated by Django 4.1.2 on 2022-10-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='employer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.employer'),
            preserve_default=False,
        ),
    ]
