# Generated by Django 4.1.2 on 2022-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_apply_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_image',
            field=models.ImageField(blank=True, default='images/employer/default_profile.png', max_length=255, null=True, upload_to='images/employer'),
        ),
    ]
