# Generated by Django 4.1.2 on 2022-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_employer_employer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer_image',
            field=models.ImageField(default='images/employer/default_profile.png', max_length=255, upload_to='images/employee'),
        ),
    ]
